update workflow

diff --git a/.github/workflows/maven.yml b/.github/workflows/maven.yml
--- a/.github/workflows/maven.yml
+++ b/.github/workflows/maven.yml
@@ -47,9 +47,11 @@ jobs:
              ./target/tambola-gen-${{ runner.os == 'macOS' && 'arm64' || (runner.os == 'Windows' && 'windows' || 'linux') }}${{ runner.os == 'Windows' && '.exe' || '' }}
 
       - name: Debug GITHUB_TOKEN
-        env:
-          TOKEN: ${{ secrets.GITHUB_TOKEN }}
-        run: echo "Token is available"
+        run: |
+          if [ -z "${{ secrets.GITHUB_TOKEN }}" ]; then
+            echo "GITHUB_TOKEN is missing!"
+            exit 1
+          fi
 
       - name: Create Release
         if: startsWith(github.ref, 'refs/tags/v')
